<?php

namespace AppBundle\Repository;

/**
 * CrawlerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrawlerRepository extends \Doctrine\ORM\EntityRepository
{
}
