<?php

namespace AppBundle\Repository;

/**
 * NewspaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewspaperRepository extends \Doctrine\ORM\EntityRepository
{
}
